### PR TITLE
Select the correct city. 

### PR DESCRIPTION
**Pull request by denzyldick**
Hi,

I added the ability to select the correct city(#5). 
I also found out the open weather API response sometimes contains duplicate rows.
[Screencast](https://user-images.githubusercontent.com/2477646/205884042-eb5f65ef-cca9-4bb5-a993-c5ad16844395.webm)

### CODE REVIEW

**Comment by eoin-barr** [comment]
Really nice work ! Thought from a UX point of view it might be nice if users could select the city using arrow keys and the enter key. Lmk if you want to implement it 👍

**Comment by denzyldick** [comment]
I will implement it.

**Comment by denzyldick** [comment]
Is there a specific terminal UI package that you want me to use?

**Comment by eoin-barr** [comment]
I quite like the way eslint do their selections which is pretty simple but looks good. I think you should be able to do it with https://github.com/gizak/termui lists, but I don't mind what package you use !
eslint

**Comment by eoin-barr** [comment]
Nice work 🚀

**Pull request merged**
