### PR TITLE
Format sunrise and sunset

### PR DESCRIPTION
**Pull request by getninjaN**

### CODE REVIEW

**Comment by eoin-barr** [comment]
Thanks for the pr ! This seems to convert the Sunrise & Sunset to the user's local time which works for locations in the same time zone, however, for cities outside of their timezone it still uses their timezone. Would be nice to have it so that it shows the times adjusted for the time zone of the city selected.

**Comment by getninjaN** [comment]
Oh! Yeah, you're right. :)
I'll fix!

**Comment by getninjaN** [comment]
I'm now calculating the Time with the Timezone offset returned by the API. After some tests it matches what is shown on Open Weather.

**Comment by eoin-barr** [comment]
Great work 🚀

**Pull request merged**
